apiVersion: v2
name: labs-infra-vkecluster
version: 0.1.0
description: A Helm chart for Kubernetes
type: application
home: "https://github.com/jhegner/kubernetes-labs"
icon: "https://github.com/jhegner/kubernetes-labs/blob/main/images/k8s_lab_path.png"
keywords:
  - vke
  - vkecluster
  - cluster
  - infrastructure
  - labs
  - vultr
sources:
  - "https://github.com/jhegner/kubernetes-labs-infra-vkecluster"
maintainers:
  - name: jhegner
    email: "jhegner@mail.com"
dependencies:
  - name: external-secrets
    version: "0.19.2"
    repository: "https://charts.external-secrets.io"