apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.secretStoreName }} 
  namespace: {{ .Values.namespaceName }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.region }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: {{ .Values._awsIamCredencialName }}
            key: accessKey
          secretAccessKeySecretRef:
            name: {{ .Values._awsIamCredencialName }}
            key: secretKey