name: CI/CD Deploy Infra 🚀

on:
  workflow_dispatch:

jobs:
  ci-feature:
    uses: jhegner/kubernetes-labs-ci-workflows/.github/workflows/3.1-reusable-deploy-infra.yml@develop
    with:
      bucket-tf-backend-name: "kubernetes-labs-tf-backend-aws-s3bucket"
      key-tf-backend-name: "lab/state/tf-infra-vkecluster"
      have-helm-charts: true
      helm-charts-namespace: labs
      install-helm-charts-workload: true
    secrets:
      VULTR_API_KEY: ${{ secrets.VULTR_API_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
